Ruff cutover

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -32,7 +32,8 @@ jobs:
       - name: Run sqlfluff on jinja templates
         run: |
           sqlfluff lint
-      - name: Run black
-        if: success() || failure() # still run black if above checks fails
+            - name: Run ruff
+        if: success() || failure() # still run ruff if above checks fails
         run: |
-          black --check --verbose .
+          ruff check
+          ruff format --check
