Moved study period source from core (#41)
* Moved study period source from core

This takes the core__study_period table (which was really
specific to this study) and moves it into this study as part
of the covid_symptom__study_period table.

This also removes the no longer required interstitial directory,
and updates the counts builder/pyproject.toml to the 3.0 input
format.

* Ruff cutover

* ci indenting, more generic args

* removed unused imports

* ruff format

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -10,12 +10,21 @@ jobs:
       - name: Set up Python 
         uses: actions/setup-python@v4
         with:
-          python-version: "3.10"
+          python-version: "3.11"
 
   lint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+
+      - name: Set up Python 
+        uses: actions/setup-python@v4
+        with:
+          python-version: "3.11"
+
+      - name: Get library from main
+        run: pip install git+https://github.com/smart-on-fhir/cumulus-library.git
+      
       - name: Install linters
         run: |
           python -m pip install --upgrade pip
@@ -23,7 +32,8 @@ jobs:
       - name: Run sqlfluff on jinja templates
         run: |
           sqlfluff lint
-      - name: Run black
-        if: success() || failure() # still run black if above checks fails
+      - name: Run ruff
+        if: success() || failure() # still run ruff if above checks fails
         run: |
-          black --check --verbose .
+          ruff check
+          ruff format --check
